@Todo.Api_HostAddress = http://localhost:5200

### ==========================================================
### TẬP 1: TƯƠNG TÁC VỚI TODOS
### ==========================================================

### 1. Tạo mới một Todo Item (POST)
# Sau khi chạy, hãy copy lấy cái "id" ở phần phản hồi trả về để dán vào các test bên dưới
POST {{Todo.Api_HostAddress}}/api/todos
Content-Type: application/json

{
  "title": "Test Reminder Scanner",
  "dueAt": "2026-07-28T15:00:00Z" 
}

###

### 2. Lấy TOÀN BỘ danh sách Todo (Không truyền filter)
GET {{Todo.Api_HostAddress}}/api/todos
Accept: application/json

###

### 3. Lấy TOÀN BỘ danh sách Todo (Truyền filter = all)
GET {{Todo.Api_HostAddress}}/api/todos?filter=all
Accept: application/json

###

### 4. Lấy danh sách Todo chưa hoàn thành (filter = active)
GET {{Todo.Api_HostAddress}}/api/todos?filter=active
Accept: application/json

###

### 5. Lấy danh sách Todo đã hoàn thành (filter = completed)
GET {{Todo.Api_HostAddress}}/api/todos?filter=completed
Accept: application/json

###

### 6. Lấy chi tiết một Todo theo ID (GET {id})
# Lấy ID ở bước 1 dán vào đây
GET {{Todo.Api_HostAddress}}/api/todos/6a5e24bbaf734b4023b46816
Accept: application/json

###

### 7. Cập nhật (Sửa) toàn bộ Todo (PUT)
# Thay ID trên URL bằng ID thực tế dưới DB
PUT {{Todo.Api_HostAddress}}/api/todos/6a5e24bbaf734b4023b46816
Content-Type: application/json

{
  "title": "Cập nhật Title mới cho Todo",
  "isCompleted": false
}

###

### 8. Đảo trạng thái hoàn thành (PATCH Toggle)
# Bắn API này sẽ làm IsCompleted đảo ngược (true <-> false) VÀ tự động trigger event dọn rác Reminder!
PATCH {{Todo.Api_HostAddress}}/api/todos/6a5e24bbaf734b4023b46816/toggle

###

### 9. Xóa một Todo đơn lẻ theo ID (DELETE {id})
DELETE {{Todo.Api_HostAddress}}/api/todos/6a5e24bbaf734b4023b46816

###

### 10. Dọn sạch toàn bộ các Todo đã hoàn thành (DELETE Clear Completed)
DELETE {{Todo.Api_HostAddress}}/api/todos/completed

###


### ==========================================================
### TẬP 2: TƯƠNG TÁC VỚI REMINDERS (NHẮC NHỞ)
### ==========================================================

### 11. Lấy danh sách Reminder đang chờ (Pending)
# Sau khi Bot Scanner chạy (30s), chạy API này để lấy ID của Reminder
GET {{Todo.Api_HostAddress}}/api/reminders?state=pending
Accept: application/json

###

### 12. Lấy danh sách Todo sắp tới hạn (Upcoming trong 24h tới)
# API này query thẳng vào bảng TodoItem
GET {{Todo.Api_HostAddress}}/api/reminders/upcoming?within=24h
Accept: application/json

###

### 13. Ngủ nướng (Snooze Reminder)
# Thay chữ REMINDER_ID_HERE bằng cái "id" lấy được từ kết quả của Bước 11
PATCH {{Todo.Api_HostAddress}}/api/reminders/6a67fdd65474331f2320ced5/snooze
Content-Type: application/json

{
  "minutes": 10
}

###

### 14. Tắt chuông hoàn toàn (Dismiss Reminder)
# Thay chữ REMINDER_ID_HERE bằng cái "id" lấy được từ kết quả của Bước 11
PATCH {{Todo.Api_HostAddress}}/api/reminders/REMINDER_ID_HERE/dismiss

###