@HostAddress = http://localhost:5100

### =========================================
### 1. TODOS API TEST CASES
### =========================================

### Lấy toàn bộ danh sách Todo (Tùy chọn: filter=all|active|completed)
GET {{HostAddress}}/bff/todos
Accept: application/json

---

### Tạo mới Todo (Lỗi 400 - Test Validation Title rỗng)
POST {{HostAddress}}/bff/todos
Content-Type: application/json

{
  "title": ""
}

---

### Tạo mới Todo (Thành công 200)
POST {{HostAddress}}/bff/todos
Content-Type: application/json

{
  "title": "Test M3 cho xong"
}

---

# Gán ID của Todo vừa tạo vào biến này để test các request dưới
@TodoId = 6a5e40dc027cf5045e0e0ac6

### Lấy chi tiết Todo theo ID
GET {{HostAddress}}/bff/todos/{{TodoId}}
Accept: application/json

---

### Cập nhật Todo (Đổi Title và set IsCompleted = true)
PUT {{HostAddress}}/bff/todos/{{TodoId}}
Content-Type: application/json

{
  "title": "Học xong Minimal API (Update)",
  "isCompleted": true
}

---

### Đảo ngược trạng thái Todo (Toggle)
PATCH {{HostAddress}}/bff/todos/{{TodoId}}/toggle

---

### Xóa 1 Todo cụ thể
DELETE {{HostAddress}}/bff/todos/{{TodoId}}

---

### Dọn rác: Xóa toàn bộ Todo đã hoàn thành
DELETE {{HostAddress}}/bff/todos/completed


### =========================================
### 2. STATISTICS API TEST CASES
### =========================================

### Lấy dữ liệu thống kê tổng quan (Overview)
GET {{HostAddress}}/bff/stats/overview
Accept: application/json